services:
  - type: web
    name: anh-va-nho
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
